
spring.application.name=Smart-Workplace-Management-Portal
server.port=8080


# JWT SECURITY CONFIGURATION
# JWT Secret Key (Base64 encoded )
application.security.jwt.secret-key=${JWT_SECRET_KEY }
spring.jpa.hibernate.ddl-auto=update

# 86400000 ms = 24 hours
application.security.jwt.expiration=86400000

# 604800000 ms = 7 days
application.security.jwt.refresh-token-expiration=604800000



# DATABASE CONFIGURATION
spring.datasource.url = ${SPRING_DATASOURCE_URL }
spring.datasource.driver-class-name=org.postgresql.Driver


# Cache configuration
spring.cache.type=caffeine
spring.cache.cache-names=userDetailsCache
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10m


# LOGGING CONFIGURATION
# Root logging level
logging.level.root=INFO

# Spring Framework logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG

# Hibernate logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Application logging
logging.level.com.example.Smart.Workplace.Management.Portal=DEBUG


#GROQ CONFIGURATION
groq.api.key=${GROQ_API_KEY}
groq.model= ${GROQ_MODEL}